#!/usr/bin/env python3
import sys
from syntesim.simulator import State, Event
from numpy.random import default_rng, Generator
from dataclasses import field
from syntesim.model import Gene, IdGenerator, Species, Synteny

state = State.unit()
state.generator = default_rng(int(sys.argv[1]))

input = open("Simulation.json","w")
state.log_to(input)

weights = {
    Event.Speciation: 6,
    Event.Extinction: 1,
    Event.Duplication: 4,
    Event.Transfer: 2,
    Event.Gain: 5,
    Event.Loss: 1,
    Event.Cut: 1,
    Event.Join: 0,
}

Continue = True

while (len(state.species) < 10) and Continue == True:
    try:      
        state.event(weights)
    except:
        Continue = False

input.close()